'use strict';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='a-la-mesa-v1', VIEW_KEY='a-la-mesa-view-week', SYNC_KEY='a-la-mesa-last-sync', UNDO_KEY='a-la-mesa-undo-v3', NOTICE_KEY='a-la-mesa-notices-v3';
const API_URL='https://script.google.com/macros/s/AKfycbyLr8kf7iwpyHsPXoQXEPdpQIgH9kmzyvTfFfL885MiIxXoIx4JhddlDiwWLzibndZHHQ/exec';
const now=()=>Date.now(), uid=()=>crypto.randomUUID(), DAY=86400000;
let viewWeekOffset=Number(localStorage.getItem(VIEW_KEY)||0), currentInventoryLocation='fridge', currentMoreTab='leftovers';
let pendingMenuSlot=null, draftIngredients=[], selectedPlan=null, scanner=null, scanLocked=false, remoteSaveTimer=null, lastSyncedAt=Number(localStorage.getItem(SYNC_KEY)||0), autoDraft=[];

const CATEGORY_INFO={
  other:{label:'Otros',days:90,freeze:'Congela en recipientes o bolsas aptos, retirando el máximo aire posible.',thaw:'Descongela en la nevera, nunca a temperatura ambiente.',after:'Consume cuanto antes y sigue la etiqueta del fabricante.'},
  ground_meat:{label:'Carne picada / hamburguesas',days:105,freeze:'Divide en raciones y separa las piezas para sacar solo las necesarias.',thaw:'Pasa a la nevera la noche anterior y cocina completamente.',after:'Cocina en 1–2 días después de descongelar.'},
  red_meat:{label:'Filetes, chuletas y asados',days:240,freeze:'Envuelve bien cada pieza para evitar quemaduras por frío.',thaw:'Descongela lentamente en la nevera.',after:'Utiliza en 3–5 días según la pieza.'},
  poultry:{label:'Pollo o pavo en piezas',days:270,freeze:'Congela por raciones y etiqueta la fecha.',thaw:'Pasa a la nevera con 24 horas de antelación; evita lavar el pollo crudo.',after:'Cocina en 1–2 días.'},
  poultry_whole:{label:'Pollo o pavo entero',days:365,freeze:'Protege bien toda la superficie y deja espacio para una congelación rápida.',thaw:'Necesita normalmente 1–2 días en la nevera según tamaño.',after:'Cocina en 1–2 días.'},
  fatty_fish:{label:'Pescado graso',days:75,freeze:'Seca, envuelve herméticamente y congela lo antes posible.',thaw:'Descongela en la nevera. Para consumo crudo aplica la prevención de anisakis.',after:'Consume en 1 día.'},
  lean_fish:{label:'Pescado blanco',days:210,freeze:'Limpia, seca y envasa sin aire.',thaw:'Descongela en la nevera; para consumo crudo aplica la prevención de anisakis.',after:'Consume en 1–2 días.'},
  shellfish:{label:'Marisco',days:90,freeze:'Congela muy fresco y bien protegido.',thaw:'Descongela en la nevera o cocina directamente si la etiqueta lo indica.',after:'Consume en 1–2 días.'},
  cooked:{label:'Plato cocinado / sobras',days:90,freeze:'Enfría rápidamente, divide en porciones y congela antes de dos horas.',thaw:'Descongela en la nevera o recalienta directamente hasta que esté muy caliente.',after:'Consume en 3–4 días y recalienta una sola vez.'},
  bread:{label:'Pan y bollería',days:90,freeze:'Congela en porciones o rebanadas para sacar solo lo necesario.',thaw:'Puede descongelarse a temperatura ambiente poco tiempo o tostarse directamente.',after:'Consume pronto para mantener la textura.'},
  vegetables:{label:'Verduras',days:300,direct:true,freeze:'Muchas verduras conservan mejor color y textura si se escaldan antes.',thaw:'Cocina directamente congeladas cuando sea posible.',after:'Utiliza una vez descongeladas.'},
  pizza:{label:'Pizza / quiche',days:60,direct:true,freeze:'Protege bien las porciones y etiqueta la fecha.',thaw:'Suele poder cocinarse directamente congelada; comprueba la receta o etiqueta.',after:'Consume tras cocinar.'},
  dairy:{label:'Lácteos',days:60,freeze:'La textura puede cambiar; deja espacio en líquidos para que se expandan.',thaw:'Descongela en la nevera y remueve bien.',after:'Consume pronto.'}
};
const LOCATION_LABEL={fridge:'Nevera',freezer:'Congelador',pantry:'Despensa'};
const SHOP_CATEGORIES=['Fruta y verdura','Carne y pescado','Lácteos y huevos','Panadería','Despensa','Congelados','Bebidas','Limpieza','Otros'];

function localDateKey(d=new Date()){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function parseDate(s){return new Date(`${s}T12:00:00`)}
function addDays(s,n){const d=typeof s==='string'?parseDate(s):new Date(s);d.setDate(d.getDate()+n);return localDateKey(d)}
function dayDiff(a,b){return Math.floor((parseDate(a)-parseDate(b))/DAY)}
function mondayOf(offset=0){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7)+offset*7);return d}
function keyFor(date,slot){return `${typeof date==='string'?date:localDateKey(date)}_${slot}`}
function splitPlanKey(k){return {date:k.slice(0,10),slot:k.slice(11)}}
function fmtDate(d,options={day:'numeric',month:'short'}){return (typeof d==='string'?parseDate(d):d).toLocaleDateString('es-ES',options)}
function formatNumber(n){return Number(n||0).toLocaleString('es-ES',{maximumFractionDigits:2})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeUrl(v){try{const u=new URL(v,location.href);return u.protocol==='https:'?u.href:''}catch{return ''}}
function normalizedName(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function sortByName(a,b){return String(a.name||'').localeCompare(String(b.name||''),'es',{sensitivity:'base',numeric:true})}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2200)}
function categoryForName(name){const n=normalizedName(name);if(/hamburg|carne picada|alb[oó]ndiga/.test(n))return'ground_meat';if(/pollo|pavo/.test(n))return'poultry';if(/salmon|atun|caballa|sardina/.test(n))return'fatty_fish';if(/merluza|bacalao|lenguado|pescado/.test(n))return'lean_fish';if(/gamba|langost|marisco|cangrejo/.test(n))return'shellfish';if(/pizza|quiche/.test(n))return'pizza';if(/pan|croissant|boll/.test(n))return'bread';if(/sopa|guiso|cocido|sobr|lasa[nñ]a/.test(n))return'cooked';if(/verdura|judia|guisante|brocoli|espinaca/.test(n))return'vegetables';if(/leche|queso|yogur|nata/.test(n))return'dairy';if(/ternera|cerdo|cordero|filete|chuleta/.test(n))return'red_meat';return'other'}
function shopCategory(name){const n=normalizedName(name);if(/tomate|lechuga|fruta|manzana|platano|cebolla|patata|zanahoria|verdura/.test(n))return'Fruta y verdura';if(/pollo|carne|pescado|cerdo|ternera|salmon|atun/.test(n))return'Carne y pescado';if(/leche|queso|yogur|huevo|nata/.test(n))return'Lácteos y huevos';if(/pan|harina|croissant/.test(n))return'Panadería';if(/agua|zumo|vino|cerveza|refresco/.test(n))return'Bebidas';if(/detergente|jabon|limpia|papel/.test(n))return'Limpieza';return'Despensa'}

function defaultState(){return {version:3,menus:[
  {id:uid(),name:'Pizza casera',type:'dinner',time:'45 min',notes:'Viernes noche',ingredients:[],tags:['pasta'],favorite:true,noSuggest:false,updatedAt:0},
  {id:uid(),name:'Quiche de verduras',type:'both',time:'50 min',notes:'',ingredients:[],tags:['huevo','verduras'],favorite:false,noSuggest:false,updatedAt:0},
  {id:uid(),name:'Albóndigas de pollo con arroz',type:'meal',time:'40 min',notes:'',ingredients:[],tags:['pollo'],favorite:false,noSuggest:false,updatedAt:0}
],plans:{},leftovers:[],shop:[],inventory:[],templates:[],history:[],productCache:{},settings:{allergens:[],reminderTime:'20:00',notifyThaw:true,notifyExpiry:true,notifyConfirm:true},shopDismissedByWeek:{},shopHiddenByWeek:{},deletedIds:{menus:{},plans:{},leftovers:{},shop:{},inventory:{},templates:{}},updatedAt:0}}
function normIngredient(i,index=0){if(typeof i==='string')return{id:`legacy-${index}-${normalizedName(i)}`,name:i,quantity:null,unit:''};return{id:i.id||uid(),name:String(i.name||''),quantity:i.quantity===''||i.quantity==null?null:Number(i.quantity),unit:String(i.unit||'')}}
function normalizeState(raw){
  const base=defaultState(), r=raw&&typeof raw==='object'?raw:{}, overall=Number(r.updatedAt||0), out={...base,...r};
  out.menus=(Array.isArray(r.menus)?r.menus:base.menus).map(m=>({...m,id:m.id||uid(),name:String(m.name||''),type:['meal','dinner','both'].includes(m.type)?m.type:'both',ingredients:(m.ingredients||[]).map(normIngredient),tags:Array.isArray(m.tags)?m.tags:inferTags(m),favorite:Boolean(m.favorite),noSuggest:Boolean(m.noSuggest),updatedAt:Number(m.updatedAt||overall)}));
  out.plans=r.plans&&typeof r.plans==='object'?r.plans:{};Object.keys(out.plans).forEach(k=>{const list=Array.isArray(out.plans[k])?out.plans[k]:(out.plans[k]?[out.plans[k]]:[]);out.plans[k]=list.map((p,i)=>({...p,id:p.id||`legacy-${k}-${i}`,kind:p.kind||'menu',updatedAt:Number(p.updatedAt||overall)}))});
  out.leftovers=(Array.isArray(r.leftovers)?r.leftovers:[]).map(x=>({...x,id:x.id||uid(),updatedAt:Number(x.updatedAt||overall)}));
  out.shop=(Array.isArray(r.shop)?r.shop:[]).filter(x=>x.source!=='auto'&&x.source!=='menu').map(x=>({...x,id:x.id||uid(),quantity:x.quantity==null?null:Number(x.quantity),category:x.category||shopCategory(x.name),updatedAt:Number(x.updatedAt||overall)}));
  const legacy=(Array.isArray(r.freezer)?r.freezer:[]).map(x=>({id:x.id||uid(),name:x.name,brand:x.brand||'',barcode:x.barcode||'',quantity:Number(x.quantity)||1,unit:x.unit||'ud',location:'freezer',storedAt:x.frozenAt||localDateKey(),expiryAt:'',openedAt:'',category:x.category||categoryForName(x.name),qualityDays:Number(x.qualityDays)||CATEGORY_INFO[x.category||categoryForName(x.name)]?.days||90,notes:x.notes||'',imageUrl:x.imageUrl||'',allergens:x.allergens||[],updatedAt:Number(x.updatedAt||overall)}));
  const inventory=Array.isArray(r.inventory)?r.inventory:legacy;out.inventory=inventory.map(x=>({...x,id:x.id||uid(),name:String(x.name||''),quantity:Number(x.quantity)||1,unit:x.unit||'ud',location:['fridge','freezer','pantry'].includes(x.location)?x.location:'fridge',storedAt:x.storedAt||x.frozenAt||localDateKey(),expiryAt:x.expiryAt||'',openedAt:x.openedAt||'',category:x.category||categoryForName(x.name),qualityDays:Number(x.qualityDays)||CATEGORY_INFO[x.category||categoryForName(x.name)]?.days||90,allergens:Array.isArray(x.allergens)?x.allergens:[],updatedAt:Number(x.updatedAt||overall)}));
  out.templates=(Array.isArray(r.templates)?r.templates:[]).map(x=>({...x,id:x.id||uid(),updatedAt:Number(x.updatedAt||overall)}));out.history=Array.isArray(r.history)?r.history.slice(0,250):[];out.productCache=r.productCache&&typeof r.productCache==='object'?r.productCache:{};
  out.settings={...base.settings,...(r.settings||{}),allergens:Array.isArray(r.settings?.allergens)?r.settings.allergens:[]};out.shopDismissedByWeek=r.shopDismissedByWeek&&typeof r.shopDismissedByWeek==='object'?r.shopDismissedByWeek:{};out.shopHiddenByWeek=r.shopHiddenByWeek&&typeof r.shopHiddenByWeek==='object'?r.shopHiddenByWeek:{};
  const del=r.deletedIds||{};out.deletedIds={menus:{},plans:{},leftovers:{},shop:{},inventory:{},templates:{}};Object.keys(out.deletedIds).forEach(k=>out.deletedIds[k]=del[k]&&typeof del[k]==='object'?del[k]:{});
  out.version=3;out.updatedAt=overall;delete out.freezer;delete out.weekOffset;return out
}
function inferTags(menu){const n=normalizedName(`${menu.name||''} ${(menu.ingredients||[]).map(i=>typeof i==='string'?i:i.name).join(' ')}`),tags=[];for(const t of ['pollo','pavo','vacuno','cerdo','pescado','marisco','huevo','legumbres','pasta','arroz','verduras'])if(n.includes(t)||t==='vacuno'&&/ternera|hamburguesa/.test(n)||t==='legumbres'&&/lenteja|garbanzo|judia/.test(n))tags.push(t);return tags}
function loadState(){try{return normalizeState(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return defaultState()}}
let state=loadState(), lastSnapshot=JSON.stringify(state);
function storeLocal(){localStorage.setItem(KEY,JSON.stringify(state));lastSnapshot=JSON.stringify(state)}
function tombstone(type,id,t=now()){state.deletedIds[type][id]=Math.max(Number(state.deletedIds[type][id]||0),t)}
function removeFrom(type,id){state[type]=state[type].filter(x=>x.id!==id);tombstone(type,id)}
function flattenPlans(plans){return Object.entries(plans).flatMap(([key,list])=>(list||[]).map(x=>({...x,_key:key})))}
function mergeDeleted(a,b){const out={menus:{},plans:{},leftovers:{},shop:{},inventory:{},templates:{}};Object.keys(out).forEach(k=>[a?.[k]||{},b?.[k]||{}].forEach(src=>Object.entries(src).forEach(([id,t])=>out[k][id]=Math.max(Number(out[k][id]||0),Number(t||0)))));return out}
function mergeArray(local,remote,type,deleted){const map=new Map();[...remote,...local].forEach(x=>{const old=map.get(x.id);if(!old||Number(x.updatedAt||0)>=Number(old.updatedAt||0))map.set(x.id,x)});return[...map.values()].filter(x=>Number(deleted[type][x.id]||0)<Number(x.updatedAt||0))}
function mergeStates(a,b){const l=normalizeState(a),r=normalizeState(b),deleted=mergeDeleted(l.deletedIds,r.deletedIds),m={...l,deletedIds:deleted};for(const type of ['menus','leftovers','shop','inventory','templates'])m[type]=mergeArray(l[type],r[type],type,deleted);const plans=mergeArray(flattenPlans(l.plans),flattenPlans(r.plans),'plans',deleted);m.plans={};plans.forEach(({_key,...p})=>(m.plans[_key]??=[]).push(p));m.history=[...l.history,...r.history].sort((x,y)=>Number(y.at||0)-Number(x.at||0)).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,250);m.productCache={...r.productCache,...l.productCache};m.settings=Number(l.updatedAt)>=Number(r.updatedAt)?l.settings:r.settings;m.shopDismissedByWeek={...r.shopDismissedByWeek,...l.shopDismissedByWeek};m.shopHiddenByWeek={...r.shopHiddenByWeek,...l.shopHiddenByWeek};for(const prop of ['shopDismissedByWeek','shopHiddenByWeek'])for(const k of new Set([...Object.keys(l[prop]),...Object.keys(r[prop])]))m[prop][k]=[...new Set([...(l[prop][k]||[]),...(r[prop][k]||[])])];m.updatedAt=Math.max(Number(l.updatedAt||0),Number(r.updatedAt||0));return normalizeState(m)}
function checkpoint(){const current=JSON.stringify(state);if(current===lastSnapshot)return;const stack=JSON.parse(localStorage.getItem(UNDO_KEY)||'[]');stack.unshift(lastSnapshot);localStorage.setItem(UNDO_KEY,JSON.stringify(stack.slice(0,12)));lastSnapshot=current}
function addHistory(action,detail,extra={}){state.history.unshift({id:uid(),at:now(),action,detail,...extra});state.history=state.history.slice(0,250)}
function persist(message='Guardado',sync=true){checkpoint();state.updatedAt=now();storeLocal();updateUndo();$('#saveStatus').textContent=sync?'Guardando…':'Guardado';renderAlertsBadge();if(sync){clearTimeout(remoteSaveTimer);remoteSaveTimer=setTimeout(()=>saveRemote(message),650)}else toast(message)}
function updateUndo(){$('#undoBtn').disabled=!JSON.parse(localStorage.getItem(UNDO_KEY)||'[]').length}
function undo(){const stack=JSON.parse(localStorage.getItem(UNDO_KEY)||'[]');if(!stack.length)return;const previous=stack.shift();localStorage.setItem(UNDO_KEY,JSON.stringify(stack));state=normalizeState(JSON.parse(previous));state.updatedAt=now();storeLocal();renderAll();saveRemote('Cambio deshecho',true);toast('Último cambio deshecho')}
async function fetchRemote(){const res=await fetch(`${API_URL}?t=${now()}`,{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);const json=await res.json();if(!json.ok)throw Error(json.error||'Error de carga');return normalizeState(json.data)}
async function saveRemote(message='Guardado en todos los dispositivos',skipPreflight=false){clearTimeout(remoteSaveTimer);$('#saveStatus').textContent='Guardando online…';try{if(!skipPreflight){const online=await fetchRemote();if(Number(online.updatedAt||0)>lastSyncedAt){state=mergeStates(state,online);state.updatedAt=now();storeLocal();renderAll()}}const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({data:state})});if(!res.ok)throw Error(`HTTP ${res.status}`);const json=await res.json();if(!json.ok)throw Error(json.error||'Error al guardar');lastSyncedAt=Number(json.updatedAt||state.updatedAt||now());localStorage.setItem(SYNC_KEY,String(lastSyncedAt));$('#saveStatus').textContent='Guardado online';toast(message)}catch(e){console.error(e);$('#saveStatus').textContent='Guardado solo aquí';toast('Sin conexión: conservado en este dispositivo')}}
async function loadRemote(show=true){$('#saveStatus').textContent='Actualizando…';try{const online=await fetchRemote();state=Number(state.updatedAt||0)===0?online:mergeStates(state,online);lastSyncedAt=Math.max(lastSyncedAt,Number(online.updatedAt||0));localStorage.setItem(SYNC_KEY,String(lastSyncedAt));storeLocal();renderAll();$('#saveStatus').textContent='Datos al día';if(show)toast('Datos actualizados');if(JSON.stringify(state)!==JSON.stringify(online))saveRemote('Cambios combinados',true)}catch(e){console.error(e);$('#saveStatus').textContent='Usando copia local';renderAll();if(show)toast('No se pudo conectar; se usa la copia local')}}

function getPlans(key){return Array.isArray(state.plans[key])?state.plans[key]:[]}
function addPlan(key,data){(state.plans[key]??=[]).push({id:uid(),kind:'menu',done:false,updatedAt:now(),...data})}
function removePlan(key,id){const list=getPlans(key),item=list.find(x=>x.id===id);if(item)tombstone('plans',id);state.plans[key]=list.filter(x=>x.id!==id);if(!state.plans[key].length)delete state.plans[key]}
function currentWeekId(){return localDateKey(mondayOf(viewWeekOffset))}
function weekKeys(offset=viewWeekOffset){const start=mondayOf(offset);return Array.from({length:7},(_,i)=>addDays(start,i))}
function weekPlanEntries(offset=viewWeekOffset){const dates=new Set(weekKeys(offset));return Object.entries(state.plans).filter(([k])=>dates.has(k.slice(0,10)))}
function menuForPlan(p){return state.menus.find(m=>m.id===p.menuId)}
function inventoryForPlan(p){return state.inventory.find(i=>i.id===p.inventoryItemId)}
function reservedQuantity(itemId,excludePlanId=''){let total=0;Object.values(state.plans).flat().forEach(p=>{if(p.kind==='inventory'&&p.inventoryItemId===itemId&&!p.done&&p.id!==excludePlanId)total+=Number(p.quantity||0)});return Number(total.toFixed(2))}
function availableQuantity(item,excludePlanId=''){return Math.max(0,Number((Number(item.quantity)-reservedQuantity(item.id,excludePlanId)).toFixed(2)))}
function renderAll(){renderWeek();renderMenus();renderShop();renderInventory();renderMore();renderAlertsBadge();updateUndo();renderAutoUnlock()}
function renderWeek(){
  const start=mondayOf(viewWeekOffset),end=addDays(start,6);$('#weekTitle').textContent=`${fmtDate(start)} – ${fmtDate(end)}`;const wrap=$('#days');wrap.innerHTML='';
  weekKeys().forEach(date=>{const d=parseDate(date),article=document.createElement('article'),past=date<localDateKey();article.className=`day ${date===localDateKey()?'today':''} ${past?'past':''}`;article.innerHTML=`<div class="day-head"><div class="day-title"><strong>${esc(d.toLocaleDateString('es-ES',{weekday:'long'}))}</strong><span>${esc(fmtDate(d))}</span></div><button class="day-save" type="button">☆ Guardar día</button></div><div class="slots"><div class="slot meal"><p class="slot-label">Comida</p>${slotHtml(date,'meal')}</div><div class="slot dinner"><p class="slot-label">Cena</p>${slotHtml(date,'dinner')}</div></div>`;
    article.querySelector('.day-save').onclick=()=>openTemplateSave('day',date);article.querySelectorAll('.add-slot').forEach(b=>b.onclick=()=>openSlot(date,b.dataset.slot));article.querySelectorAll('.plan-menu').forEach(b=>b.onclick=()=>openPlanActions(b.dataset.key,b.dataset.id));wrap.appendChild(article)
  })
}
function slotHtml(date,slot){const key=keyFor(date,slot),plans=getPlans(key),html=plans.map(p=>{
  if(p.kind==='inventory'){const item=inventoryForPlan(p);return `<article class="plan-card inventory-plan ${p.done?'done':''}"><button class="plan-menu" data-key="${key}" data-id="${p.id}" type="button">•••</button><h3>${esc(item?.name||p.itemName||'Producto no disponible')}</h3><span class="meta">${esc(formatNumber(p.quantity))} ${esc(p.unit||item?.unit||'')} · ${esc(LOCATION_LABEL[item?.location]||'Inventario')}</span><div class="tags">${p.done?'<span class="tag green">✓ Confirmado</span>':'<span class="tag blue">Reservado</span>'}</div></article>`}
  const menu=menuForPlan(p);return `<article class="plan-card ${p.done?'done':''}"><button class="plan-menu" data-key="${key}" data-id="${p.id}" type="button">•••</button><h3>${esc(menu?.name||'Menú no disponible')}</h3><span class="meta">${esc(menu?.time||'Sin tiempo indicado')}</span><div class="tags">${p.done?'<span class="tag green">✓ Comido</span>':'<span class="tag">Previsto</span>'}${p.movedFrom?'<span class="tag">Reorganizado</span>':''}${p.hasLeftovers?'<span class="tag amber">Sobras</span>':''}</div></article>`
 }).join('');return `${html}<button class="add-slot" data-slot="${slot}" type="button">+ Añadir</button>`}
function choiceButton(label,detail,fn,cls=''){const b=document.createElement('button');b.type='button';b.className=`btn choice-button ${cls}`;b.innerHTML=`<span>${esc(label)}</span>${detail?`<small>${esc(detail)}</small>`:''}`;b.onclick=fn;return b}
function openChoice(title){$('#choiceTitle').textContent=title;$('#choiceContent').innerHTML='';$('#choiceDialog').showModal();return $('#choiceContent')}
function addChoiceGroup(container,title){const p=document.createElement('p');p.className='choice-group-title';p.textContent=title;container.appendChild(p)}
function openSlot(date,slot){const box=openChoice(slot==='meal'?'Añadir a la comida':'Añadir a la cena');box.appendChild(choiceButton('+ Crear un menú nuevo','Se guardará también en Menús',()=>{$('#choiceDialog').close();editMenu(null,{date,slot})},'primary'));box.appendChild(choiceButton('❄ Añadir del inventario','Reserva una cantidad sin descontarla todavía',()=>{$('#choiceDialog').close();chooseInventoryForSlot(date,slot)}));addChoiceGroup(box,'Menús');state.menus.filter(m=>m.type==='both'||m.type===slot).sort(sortByName).forEach(m=>box.appendChild(choiceButton(`${m.favorite?'★ ':''}${m.name}`,m.tags?.join(' · '),()=>{addPlan(keyFor(date,slot),{menuId:m.id});persist('Menú añadido');$('#choiceDialog').close();renderAll()})))}
function openPlanActions(key,id){const p=getPlans(key).find(x=>x.id===id);if(!p)return;selectedPlan={key,id};const {date,slot}=splitPlanKey(key),box=openChoice(p.kind==='inventory'?(inventoryForPlan(p)?.name||'Producto'):(menuForPlan(p)?.name||'Menú'));
  if(p.kind==='inventory'){
    if(!p.done)box.appendChild(choiceButton('✓ Confirmar lo consumido','Descuenta solo la cantidad que indiques',()=>{$('#choiceDialog').close();openConsume(key,id)},'primary'));
    else box.appendChild(choiceButton('Marcar como pendiente','Volverá a reservar la cantidad',()=>{p.done=false;p.updatedAt=now();persist();$('#choiceDialog').close();renderAll()}));
    box.appendChild(choiceButton('Cambiar de día','Mantiene la reserva',()=>{$('#choiceDialog').close();openPlacement(inventoryForPlan(p),{plan:p,key})}));
  }else{
    box.appendChild(choiceButton(p.done?'Marcar como pendiente':'✓ Lo hemos comido','',()=>{p.done=!p.done;p.updatedAt=now();addHistory(p.done?'consumed_menu':'unconfirmed_menu',`${menuForPlan(p)?.name||'Menú'} · ${fmtDate(date)}`);persist();$('#choiceDialog').close();renderAll()},p.done?'':'primary'));
    box.appendChild(choiceButton('Hemos comido otro menú','Solo reorganiza una planificación futura',()=>{$('#choiceDialog').close();openSwap(key,p)}));
    box.appendChild(choiceButton('Registrar sobras','Guarda las raciones para otro día',()=>{$('#choiceDialog').close();registerLeftovers(key,p)}));
  }
  box.appendChild(choiceButton('Quitar de la semana','No descuenta nada del inventario',()=>{removePlan(key,id);persist('Quitado de la semana');$('#choiceDialog').close();renderAll()},'danger'))
}
function openSwap(key,current){const {date,slot}=splitPlanKey(key),box=openChoice('¿Qué habéis comido?');state.menus.filter(m=>m.id!==current.menuId&&(m.type==='both'||m.type===slot)).sort(sortByName).forEach(m=>box.appendChild(choiceButton(m.name,m.tags?.join(' · '),()=>{const old=current.menuId;current.menuId=m.id;current.done=true;current.updatedAt=now();const future=Object.entries(state.plans).flatMap(([k,list])=>k.slice(0,10)>date?list.map(p=>({k,p})):[]).filter(x=>x.p.menuId===m.id&&!x.p.done).sort((a,b)=>a.k.localeCompare(b.k))[0];if(future){future.p.menuId=old;future.p.movedFrom=date;future.p.updatedAt=now()}addHistory('swapped_menu',`${menuForPlan(current)?.name||m.name} sustituyó al menú previsto`);persist('Semana reorganizada');$('#choiceDialog').close();renderAll()})))}
function registerLeftovers(key,p){const menu=menuForPlan(p),servings=Number(prompt('¿Cuántas raciones han sobrado?','1'));if(!(servings>0))return;const until=prompt('Consumir antes de (AAAA-MM-DD)',addDays(localDateKey(),3));if(!/^\d{4}-\d{2}-\d{2}$/.test(until||''))return;state.leftovers.push({id:uid(),menuId:p.menuId,servings,until,updatedAt:now()});p.hasLeftovers=true;p.updatedAt=now();addHistory('leftovers',`${servings} ración(es) de ${menu?.name||'menú'}`);persist('Sobras registradas');renderAll()}

function ingredientLabel(i){return `${i.quantity?`${formatNumber(i.quantity)} `:''}${i.unit?`${i.unit} `:''}${i.name}`.trim()}
function allergenMatches(text,allergens=[]){let hay=normalizedName(`${text} ${allergens.join(' ')}`);const translations={milk:'leche lacteos',egg:'huevo',nuts:'frutos secos',peanuts:'cacahuete',soy:'soja',fish:'pescado',crustaceans:'crustaceos marisco',molluscs:'moluscos marisco',wheat:'trigo gluten'};Object.entries(translations).forEach(([en,es])=>{if(hay.includes(en))hay+=` ${es}`});return state.settings.allergens.filter(a=>hay.includes(normalizedName(a)))}
function renderMenus(){const el=$('#menuLibrary');el.innerHTML='';state.menus.slice().sort((a,b)=>Number(b.favorite)-Number(a.favorite)||sortByName(a,b)).forEach(m=>{const c=document.createElement('article'),matches=allergenMatches(`${m.name} ${(m.ingredients||[]).map(i=>i.name).join(' ')}`);c.className='menu-library-card';c.innerHTML=`<div class="card-head"><div><h3>${esc(m.name)}</h3><span class="meta">${m.type==='both'?'Comida y cena':m.type==='meal'?'Comida':'Cena'} · ${esc(m.time||'Sin tiempo')}</span></div><button class="favorite" type="button" aria-label="Favorito">${m.favorite?'★':'☆'}</button></div>${m.ingredients?.length?`<p class="meta">${esc(m.ingredients.map(ingredientLabel).join(', '))}</p>`:''}${m.notes?`<p>${esc(m.notes)}</p>`:''}<div class="tags">${(m.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${m.noSuggest?'<span class="tag red">No sugerir</span>':''}${matches.length?`<span class="tag red">⚠ ${esc(matches.join(', '))}</span>`:''}</div><div class="card-actions"><button class="btn small edit" type="button">Editar</button><button class="btn small danger delete" type="button">Eliminar</button></div>`;c.querySelector('.favorite').onclick=()=>{m.favorite=!m.favorite;m.updatedAt=now();persist(m.favorite?'Añadido a favoritos':'Quitado de favoritos');renderMenus()};c.querySelector('.edit').onclick=()=>editMenu(m.id);c.querySelector('.delete').onclick=()=>deleteMenu(m);el.appendChild(c)});if(!el.children.length)el.innerHTML='<div class="empty-state">Aún no hay menús.</div>'}
function renderIngredientDraft(){const el=$('#ingredientList');el.innerHTML='';draftIngredients.forEach((i,index)=>{const c=document.createElement('span');c.className='chip';c.innerHTML=`${esc(ingredientLabel(i))}<button type="button">×</button>`;c.querySelector('button').onclick=()=>{draftIngredients.splice(index,1);renderIngredientDraft()};el.appendChild(c)})}
function addDraftIngredient(){const name=$('#ingredientInput').value.trim(),quantity=$('#ingredientQuantity').value,unit=$('#ingredientUnit').value;if(!name)return;draftIngredients.push({id:uid(),name,quantity:quantity?Number(quantity):null,unit});$('#ingredientInput').value='';$('#ingredientQuantity').value='';renderIngredientDraft();$('#ingredientInput').focus()}
function editMenu(id=null,slot=null){const m=state.menus.find(x=>x.id===id);pendingMenuSlot=m?null:slot;$('#menuDialogTitle').textContent=m?'Editar menú':slot?'Crear y añadir menú':'Nuevo menú';$('#menuId').value=m?.id||'';$('#menuName').value=m?.name||'';$('#menuType').value=m?.type||(slot?.slot||'both');$('#menuTime').value=m?.time||'';$('#menuNotes').value=m?.notes||'';$('#menuFavorite').checked=Boolean(m?.favorite);$('#menuNoSuggest').checked=Boolean(m?.noSuggest);[...$('#menuTags').options].forEach(o=>o.selected=(m?.tags||[]).includes(o.value));draftIngredients=(m?.ingredients||[]).map(i=>({...i}));renderIngredientDraft();$('#menuDialog').showModal()}
function deleteMenu(m){if(!confirm(`¿Borrar "${m.name}"? También se quitará de la semana y se eliminarán sus sobras.`))return;Object.keys(state.plans).forEach(k=>{getPlans(k).filter(p=>p.menuId===m.id).forEach(p=>tombstone('plans',p.id));state.plans[k]=getPlans(k).filter(p=>p.menuId!==m.id);if(!state.plans[k].length)delete state.plans[k]});state.leftovers.filter(x=>x.menuId===m.id).forEach(x=>tombstone('leftovers',x.id));state.leftovers=state.leftovers.filter(x=>x.menuId!==m.id);removeFrom('menus',m.id);addHistory('deleted_menu',m.name);persist('Menú eliminado');renderAll()}

function inventoryStatus(item){const today=localDateKey(),age=Math.max(0,-dayDiff(item.storedAt,today)),reasons=[];let level='normal',remaining=null;if(item.expiryAt){const d=dayDiff(item.expiryAt,today);if(d<0){level='danger';reasons.push(`Caducó hace ${Math.abs(d)} día(s)`)}else if(d<=3){level='warning';reasons.push(`Caduca en ${d} día(s)`)}}
  if(item.location==='freezer'){const days=Number(item.qualityDays)||CATEGORY_INFO[item.category]?.days||90,elapsed=dayDiff(today,item.storedAt);remaining=days-elapsed;if(elapsed>=days){level='danger';reasons.push('Periodo de calidad recomendado superado')}else if(elapsed>=days*.75&&level!=='danger'){level='warning';reasons.push(`Quedan unos ${Math.max(0,remaining)} días de calidad recomendada`)}}
  if(item.openedAt){const opened=dayDiff(today,item.openedAt);if(opened>=5&&level==='normal'){level='warning';reasons.push(`Abierto hace ${opened} días`)}}
  return{level,reasons,age,remaining}}
function inventoryIcon(location){return location==='freezer'?'❄️':location==='fridge'?'🥬':'🥫'}
function renderInventory(){const el=$('#inventoryList');el.innerHTML='';let list=state.inventory.filter(i=>currentInventoryLocation==='priority'?inventoryStatus(i).level!=='normal':i.location===currentInventoryLocation);list.sort((a,b)=>{const sa=inventoryStatus(a),sb=inventoryStatus(b);return (sa.level==='danger'?-2:sa.level==='warning'?-1:0)-(sb.level==='danger'?-2:sb.level==='warning'?-1:0)||String(a.storedAt).localeCompare(String(b.storedAt))||sortByName(a,b)});let totalReserved=0;
  list.forEach(item=>{const status=inventoryStatus(item),reserved=reservedQuantity(item.id),available=availableQuantity(item);totalReserved+=reserved;const img=safeUrl(item.imageUrl),matches=allergenMatches(item.name,item.allergens),c=document.createElement('article');c.className=`inventory-card ${status.level==='normal'?'':status.level}`;c.innerHTML=`${img?`<img class="inventory-photo" src="${esc(img)}" alt="">`:`<div class="inventory-photo placeholder">${inventoryIcon(item.location)}</div>`}<div><div class="card-head"><h3>${esc(item.name)}</h3><span class="tag">${esc(LOCATION_LABEL[item.location])}</span></div>${item.brand?`<div class="meta">${esc(item.brand)}</div>`:''}<div class="stock-line"><span class="quantity-line">${formatNumber(item.quantity)} ${esc(item.unit)}</span>${reserved?`<div class="meta">Disponible: ${formatNumber(available)} · reservado: ${formatNumber(reserved)}</div>`:''}</div><div class="meta">Guardado: ${esc(fmtDate(item.storedAt))}${item.expiryAt?` · caduca: ${esc(fmtDate(item.expiryAt))}`:''}</div>${item.notes?`<div class="meta">${esc(item.notes)}</div>`:''}<div class="tags">${matches.length?`<span class="tag red">⚠ ${esc(matches.join(', '))}</span>`:''}</div></div>${status.reasons.length?`<div class="priority-reason">${esc(status.reasons.join(' · '))}</div>`:''}<div class="card-actions"><button class="btn small plan" type="button">Añadir a semana</button>${item.location==='freezer'?'<button class="btn small move" type="button">Pasar a nevera</button><button class="btn small advice" type="button">Cómo descongelar</button>':''}<button class="btn small consume" type="button">Consumir</button><button class="btn small edit" type="button">Editar</button><button class="btn small danger discard" type="button">Desechar</button></div>`;
    c.querySelector('.plan').onclick=()=>openPlacement(item);c.querySelector('.move')?.addEventListener('click',()=>moveToFridge(item));c.querySelector('.advice')?.addEventListener('click',()=>openItemAdvice(item));c.querySelector('.consume').onclick=()=>consumeDirect(item);c.querySelector('.edit').onclick=()=>openInventoryForm(item);c.querySelector('.discard').onclick=()=>discardInventory(item);el.appendChild(c)
  });
  const label=currentInventoryLocation==='priority'?'productos que conviene consumir primero':`productos en ${LOCATION_LABEL[currentInventoryLocation]?.toLowerCase()||'el inventario'}`;$('#inventorySummary').textContent=`${list.length} ${label}${totalReserved?` · ${formatNumber(totalReserved)} unidades/cantidad reservadas`:''}`;if(!list.length)el.innerHTML=`<div class="empty-state">No hay ${label}.</div>`
}
function populateCategories(){const sel=$('#inventoryCategory');sel.innerHTML=Object.entries(CATEGORY_INFO).map(([id,x])=>`<option value="${id}">${esc(x.label)}</option>`).join('')}
function openInventoryForm(item=null,defaults={}){const x=item||defaults,location=x.location||(currentInventoryLocation==='priority'?'fridge':currentInventoryLocation);$('#inventoryDialogTitle').textContent=item?'Editar producto':'Añadir producto';$('#inventoryId').value=item?.id||'';$('#inventoryName').value=x.name||'';$('#inventoryBrand').value=x.brand||'';$('#inventoryBarcode').value=x.barcode||'';$('#inventoryLocation').value=['fridge','freezer','pantry'].includes(location)?location:'fridge';const category=x.category||categoryForName(x.name);$('#inventoryCategory').value=category;$('#inventoryQuantity').value=x.quantity||1;$('#inventoryUnit').value=x.unit||'ud';$('#inventoryStoredAt').value=x.storedAt||localDateKey();$('#inventoryExpiry').value=x.expiryAt||'';$('#inventoryOpenedAt').value=x.openedAt||'';$('#inventoryQualityDays').value=x.qualityDays||CATEGORY_INFO[category]?.days||90;$('#inventoryNotes').value=x.notes||'';$('#inventoryImage').value=x.imageUrl||'';$('#inventoryAllergens').value=JSON.stringify(x.allergens||[]);updateInventoryForm();$('#inventoryDialog').showModal()}
function updateInventoryForm(){const name=$('#inventoryName').value.trim(),brand=$('#inventoryBrand').value.trim(),url=safeUrl($('#inventoryImage').value),category=$('#inventoryCategory').value,location=$('#inventoryLocation').value,info=CATEGORY_INFO[category]||CATEGORY_INFO.other;$('#qualityField').hidden=location!=='freezer';$('#categoryTip').innerHTML=`<strong>${esc(info.label)}</strong><br>${esc(location==='freezer'?info.freeze:location==='fridge'?info.after:'Conserva en un lugar fresco, seco y sigue la etiqueta.')}`;const box=$('#productPreview');box.classList.toggle('show',Boolean(name&&(brand||url)));$('#productPreviewName').textContent=name;$('#productPreviewMeta').textContent=brand;$('#productPreviewImage').src=url||'';$('#productPreviewImage').style.display=url?'block':'none';let allergens=[];try{allergens=JSON.parse($('#inventoryAllergens').value||'[]')}catch{}const matches=allergenMatches(name,allergens),warning=$('#allergenWarning');warning.hidden=!matches.length;warning.textContent=matches.length?`Atención: puede contener ${matches.join(', ')}.`:''}
function chooseInventoryForSlot(date,slot){const box=openChoice('Añadir del inventario'),items=state.inventory.filter(i=>availableQuantity(i)>0).sort((a,b)=>String(a.storedAt).localeCompare(String(b.storedAt)));items.forEach(i=>box.appendChild(choiceButton(i.name,`${formatNumber(availableQuantity(i))} ${i.unit} disponibles · ${LOCATION_LABEL[i.location]}`,()=>{$('#choiceDialog').close();openPlacement(i,{date,slot})})));if(!items.length)box.innerHTML='<div class="empty-state">No hay cantidades disponibles.</div>'}
function openPlacement(item,options={}){if(!item){toast('Ese producto ya no está en el inventario');return}const p=options.plan;$('#placementTitle').textContent=`Añadir ${item.name}`;$('#placementItemId').value=item.id;$('#placementDate').value=options.date||p&&splitPlanKey(options.key).date||localDateKey(mondayOf(viewWeekOffset));$('#placementSlot').value=options.slot||p&&splitPlanKey(options.key).slot||'meal';$('#placementQuantity').value=p?.quantity||Math.min(1,availableQuantity(item,p?.id));$('#placementAvailable').textContent=`Disponible para reservar: ${formatNumber(availableQuantity(item,p?.id))} ${item.unit}`;$('#placementForm').dataset.planId=p?.id||'';$('#placementForm').dataset.oldKey=options.key||'';$('#placementDialog').showModal()}
function consumeDirect(item){const max=availableQuantity(item),raw=prompt(`¿Cuánto has consumido? Disponible: ${formatNumber(max)} ${item.unit}.`,String(Math.min(1,max)).replace('.',','));if(raw===null)return;const qty=Number(raw.replace(',','.'));if(!(qty>0)||qty>max){toast('Cantidad no válida o reservada para otro día');return}item.quantity=Number((item.quantity-qty).toFixed(2));item.updatedAt=now();addHistory('consumed_inventory',`${formatNumber(qty)} ${item.unit} de ${item.name}`,{itemId:item.id,quantity:qty});if(item.quantity<=0)removeFrom('inventory',item.id);persist('Consumo registrado');renderAll()}
function moveToFridge(item){const max=availableQuantity(item),raw=prompt(`¿Qué cantidad pasas a la nevera? Disponible: ${formatNumber(max)} ${item.unit}.`,String(max).replace('.',','));if(raw===null)return;const qty=Number(raw.replace(',','.'));if(!(qty>0)||qty>max){toast('Cantidad no válida o ya reservada');return}if(qty===Number(item.quantity)){item.location='fridge';item.storedAt=localDateKey();item.openedAt='';item.updatedAt=now()}else{item.quantity=Number((item.quantity-qty).toFixed(2));item.updatedAt=now();state.inventory.push({...item,id:uid(),parentLotId:item.id,quantity:qty,location:'fridge',storedAt:localDateKey(),openedAt:'',updatedAt:now()})}addHistory('moved_inventory',`${formatNumber(qty)} ${item.unit} de ${item.name}: congelador → nevera`);persist('Producto pasado a la nevera');currentInventoryLocation='fridge';syncInventoryTabs();renderAll()}
function discardInventory(item){const max=availableQuantity(item),raw=prompt(`¿Qué cantidad se ha desechado? Disponible: ${formatNumber(max)} ${item.unit}.`,String(max).replace('.',','));if(raw===null)return;const qty=Number(raw.replace(',','.'));if(!(qty>0)||qty>max){toast('Cantidad no válida');return}if(!confirm(`¿Confirmas que se han desechado ${formatNumber(qty)} ${item.unit} de ${item.name}?`))return;item.quantity=Number((item.quantity-qty).toFixed(2));item.updatedAt=now();addHistory('discarded_inventory',`${formatNumber(qty)} ${item.unit} de ${item.name}`,{itemId:item.id,itemName:item.name,quantity:qty});if(item.quantity<=0)removeFrom('inventory',item.id);persist('Producto desechado');renderAll()}
function openConsume(key,id){const p=getPlans(key).find(x=>x.id===id),item=p&&inventoryForPlan(p);if(!p||!item)return;$('#consumePlanKey').value=key;$('#consumePlanId').value=id;$('#consumeDescription').textContent=`Habías reservado ${formatNumber(p.quantity)} ${p.unit||item.unit} de ${item.name}.`;$('#consumeQuantity').max=String(Math.min(Number(item.quantity),Number(p.quantity)));$('#consumeQuantity').value=p.quantity;$('#consumeDialog').showModal()}
function reprogramPlan(){const key=$('#consumePlanKey').value,id=$('#consumePlanId').value,p=getPlans(key).find(x=>x.id===id),item=p&&inventoryForPlan(p);if(!p||!item)return;$('#consumeDialog').close();openPlacement(item,{plan:p,key})}

async function openScanner(){scanLocked=false;$('#barcodeInput').value='';$('#scannerStatus').textContent='Preparando la cámara…';$('#scannerDialog').showModal();if(!window.isSecureContext){$('#scannerStatus').textContent='La cámara necesita HTTPS. Puedes escribir el código manualmente.';return}if(typeof Html5Qrcode==='undefined'){$('#scannerStatus').textContent='El lector no está disponible. Escribe el código manualmente.';return}try{$('#reader').innerHTML='';scanner=new Html5Qrcode('reader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:150},formatsToSupport:window.Html5QrcodeSupportedFormats?[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A]:undefined},code=>{if(scanLocked)return;scanLocked=true;$('#barcodeInput').value=code;lookupBarcode(code)});$('#scannerStatus').textContent='Apunta al código de barras.'}catch(e){console.error(e);$('#scannerStatus').textContent='No se pudo abrir la cámara. Escribe el código manualmente.'}}
async function stopScanner(){if(scanner){try{if(scanner.isScanning)await scanner.stop();await scanner.clear()}catch{}scanner=null}scanLocked=false}
async function lookupBarcode(value){const code=String(value||$('#barcodeInput').value).replace(/\D/g,'');if(code.length<8){$('#scannerStatus').textContent='Introduce un código válido.';scanLocked=false;return}$('#scannerStatus').textContent='Buscando producto…';let p=state.productCache[code];try{if(!p){const res=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=code,product_name,product_name_es,brands,quantity,image_front_small_url,image_front_url,categories_tags,allergens_tags`);if(!res.ok)throw Error(`HTTP ${res.status}`);const json=await res.json();if(json.status===1){const x=json.product;p={barcode:code,name:x.product_name_es||x.product_name||'',brand:x.brands||'',notes:x.quantity?`Formato: ${x.quantity}`:'',imageUrl:x.image_front_small_url||x.image_front_url||'',allergens:x.allergens_tags||[],category:categoryForName(`${x.product_name_es||x.product_name||''} ${(x.categories_tags||[]).join(' ')}`)};state.productCache[code]=p;storeLocal()}}await stopScanner();$('#scannerDialog').close();if(p){openInventoryForm(null,{...p,quantity:1,unit:'ud',location:currentInventoryLocation==='priority'?'fridge':currentInventoryLocation,storedAt:localDateKey()});toast('Producto encontrado')}else{openInventoryForm(null,{barcode:code,location:currentInventoryLocation==='priority'?'fridge':currentInventoryLocation,storedAt:localDateKey()});toast('Producto desconocido: complétalo manualmente')}}catch(e){console.error(e);if(state.productCache[code]){await stopScanner();$('#scannerDialog').close();openInventoryForm(null,{...state.productCache[code],location:currentInventoryLocation==='priority'?'fridge':currentInventoryLocation,storedAt:localDateKey()});toast('Producto recuperado sin conexión')}else{$('#scannerStatus').textContent='No se pudo consultar. Comprueba la conexión o complétalo manualmente.';scanLocked=false}}}
function syncInventoryTabs(){$$('#inventoryTabs button').forEach(b=>b.classList.toggle('active',b.dataset.location===currentInventoryLocation))}

function ingredientKey(x){return `${normalizedName(x.name)}|${String(x.unit||'').toLowerCase()}`}
function inventoryAmountFor(ingredient){const key=normalizedName(ingredient.name),unit=String(ingredient.unit||'').toLowerCase();const exact=state.inventory.filter(i=>normalizedName(i.name)===key&&(!unit||String(i.unit||'').toLowerCase()===unit));if(exact.length)return{known:true,quantity:exact.reduce((n,i)=>n+Number(i.quantity||0),0)};const possible=state.inventory.filter(i=>normalizedName(i.name).includes(key)||key.includes(normalizedName(i.name)));return{known:false,quantity:0,possible:possible.length}}
function automaticShoppingItems(){const grouped=new Map();weekPlanEntries().forEach(([,plans])=>plans.filter(p=>p.kind==='menu').forEach(p=>{const menu=menuForPlan(p);(menu?.ingredients||[]).forEach(i=>{if(!i.name)return;const key=ingredientKey(i);if(!grouped.has(key))grouped.set(key,{id:`auto:${key}`,key,name:i.name,unit:i.unit||'',needed:0,hasQuantity:false,count:0,menus:new Set(),source:'auto',category:shopCategory(i.name)});const x=grouped.get(key);x.count++;x.menus.add(menu.name);if(Number(i.quantity)>0){x.needed+=Number(i.quantity);x.hasQuantity=true}})}));const completed=state.shopDismissedByWeek[currentWeekId()]||[],hidden=state.shopHiddenByWeek[currentWeekId()]||[];return[...grouped.values()].filter(x=>!hidden.includes(x.key)).map(x=>{const inv=inventoryAmountFor(x),buy=x.hasQuantity&&inv.known?Math.max(0,Number((x.needed-inv.quantity).toFixed(2))):x.needed;return{...x,inventory:inv,buy,done:completed.includes(x.key)}})}
function setWeekListValue(prop,key,on){const week=currentWeekId();state[prop][week]??=[];state[prop][week]=state[prop][week].filter(x=>x!==key);if(on)state[prop][week].push(key)}
function renderShop(){const el=$('#shopList');el.innerHTML='';const auto=automaticShoppingItems(),manual=state.shop.slice().sort(sortByName),items=[...auto,...manual],pending=items.filter(x=>!x.done),done=items.filter(x=>x.done);$('#shopSummary').textContent=`${pending.length} pendiente(s) · ${done.length} completado(s) · se descuenta lo disponible cuando la cantidad y la unidad coinciden`;
  const renderGroup=(title,list)=>{if(!list.length)return;const h=document.createElement('h3');h.className='keep-section-title';h.textContent=title;el.appendChild(h);list.sort((a,b)=>String(a.category).localeCompare(String(b.category),'es')||sortByName(a,b)).forEach(item=>{const row=document.createElement('label');row.className=`shop-item ${item.done?'completed':''}`;let detail='';if(item.source==='auto'){if(item.hasQuantity&&item.inventory.known)detail=item.buy>0?`Necesitas ${formatNumber(item.needed)} ${item.unit} · tienes ${formatNumber(item.inventory.quantity)} · comprar ${formatNumber(item.buy)}`:`Ya tienes suficiente (${formatNumber(item.inventory.quantity)} ${item.unit})`;else if(item.hasQuantity)detail=`Necesitas ${formatNumber(item.needed)} ${item.unit}${item.inventory.possible?' · comprueba la cantidad en casa':''}`;else detail=`Necesario para ${item.count} menú(s) · cantidad no indicada`}else detail=[item.quantity?formatNumber(item.quantity):'',item.unit||''].filter(Boolean).join(' ');
    row.innerHTML=`<input class="shop-check" type="checkbox" ${item.done?'checked':''}><span class="shop-main"><strong>${esc(item.name)}</strong>${detail?`<span class="shop-detail">${esc(detail)}</span>`:''}</span><span class="shop-category">${esc(item.category||'Otros')}</span><button class="delete-icon" type="button" aria-label="Quitar">×</button>`;row.querySelector('input').onchange=e=>{if(item.source==='auto'){setWeekListValue('shopDismissedByWeek',item.key,e.target.checked);if(e.target.checked&&(!item.inventory.known||item.buy>0))offerStorePurchased({name:item.name,quantity:item.buy||item.needed||1,unit:item.unit})}else{item.done=e.target.checked;item.updatedAt=now();if(item.done)offerStorePurchased(item)}persist(e.target.checked?'Producto completado':'Producto pendiente');renderShop()};row.querySelector('.shop-main').onclick=e=>{e.preventDefault();if(item.source==='auto')return;const value=prompt(`Cantidad para ${item.name}`,item.quantity??'');if(value===null)return;const qty=value===''?null:Number(String(value).replace(',','.'));if(qty!==null&&!(qty>=0)){toast('Cantidad no válida');return}item.quantity=qty;item.updatedAt=now();persist('Cantidad actualizada');renderShop()};row.querySelector('button').onclick=e=>{e.preventDefault();if(item.source==='auto')setWeekListValue('shopHiddenByWeek',item.key,true);else removeFrom('shop',item.id);persist('Producto quitado');renderShop()};el.appendChild(row)
  })};renderGroup('Pendientes',pending);renderGroup('Completados',done);if(!items.length)el.innerHTML='<div class="empty-state">La lista está vacía. Añade ingredientes a los menús de esta semana o incorpora un producto manualmente.</div>'
}
function offerStorePurchased(item){setTimeout(()=>{if(!confirm(`¿Quieres añadir "${item.name}" al inventario?`))return;const box=openChoice('¿Dónde lo guardas?');for(const [location,label] of Object.entries(LOCATION_LABEL))box.appendChild(choiceButton(label,'',()=>{$('#choiceDialog').close();openInventoryForm(null,{name:item.name,quantity:item.quantity||1,unit:item.unit||'ud',location,storedAt:localDateKey()})}))},50)}
function clearCompletedShopping(){const week=currentWeekId(),auto=automaticShoppingItems().filter(x=>x.done);auto.forEach(x=>setWeekListValue('shopHiddenByWeek',x.key,true));state.shop.filter(x=>x.done).forEach(x=>tombstone('shop',x.id));state.shop=state.shop.filter(x=>!x.done);persist('Completados ocultados');renderShop()}

function syncMoreTabs(){$$('#moreTabs button').forEach(b=>b.classList.toggle('active',b.dataset.more===currentMoreTab))}
function renderMore(){syncMoreTabs();if(currentMoreTab==='leftovers')renderLeftovers();else if(currentMoreTab==='templates')renderTemplates();else if(currentMoreTab==='alerts')renderAlerts($('#moreContent'));else renderHistory()}
function renderLeftovers(){const el=$('#moreContent');el.innerHTML='<div class="card-grid" id="leftoverCards"></div>';const list=$('#leftoverCards');state.leftovers.slice().sort((a,b)=>String(a.until).localeCompare(String(b.until))).forEach(l=>{const menu=state.menus.find(m=>m.id===l.menuId),c=document.createElement('article');c.className='leftover-card';c.innerHTML=`<h3>${esc(menu?.name||'Menú eliminado')}</h3><p><strong>${formatNumber(l.servings)} ración(es)</strong></p><span class="meta">Consumir antes del ${esc(fmtDate(l.until))}</span><div class="card-actions"><button class="btn small use" type="button">Añadir a semana</button><button class="btn small danger delete" type="button">Eliminar</button></div>`;c.querySelector('.use').onclick=()=>placeLeftover(l);c.querySelector('.delete').onclick=()=>{removeFrom('leftovers',l.id);persist('Sobras eliminadas');renderMore()};list.appendChild(c)});if(!list.children.length)list.innerHTML='<div class="empty-state">No hay sobras registradas.</div>'}
function placeLeftover(l){const menu=state.menus.find(m=>m.id===l.menuId);if(!menu)return;const box=openChoice('Colocar sobras en la semana');weekKeys().forEach(date=>['meal','dinner'].forEach(slot=>box.appendChild(choiceButton(`${fmtDate(date,{weekday:'short',day:'numeric'})} · ${slot==='meal'?'Comida':'Cena'}`,`${formatNumber(l.servings)} ración(es)`,()=>{addPlan(keyFor(date,slot),{menuId:l.menuId,fromLeftovers:true});removeFrom('leftovers',l.id);persist('Sobras colocadas');$('#choiceDialog').close();renderAll()}))))}
function openTemplateSave(type,date=''){const plans=type==='day'?[...getPlans(keyFor(date,'meal')),...getPlans(keyFor(date,'dinner'))]:weekPlanEntries().flatMap(([,x])=>x);if(!plans.length){toast('No hay nada planificado para guardar');return}$('#templateTitle').textContent=type==='day'?'Guardar día perfecto':'Guardar semana perfecta';$('#templateType').value=type;$('#templateDate').value=date;$('#templateName').value=type==='day'?`Día ${fmtDate(date)}`:`Semana ${fmtDate(mondayOf(viewWeekOffset))}`;$('#templateDialog').showModal()}
function serializePlan(p,key,baseDate){const {date,slot}=splitPlanKey(key);return{kind:p.kind,menuId:p.menuId,inventoryItemId:p.inventoryItemId,itemName:p.itemName,quantity:p.quantity,unit:p.unit,slot,dayOffset:dayDiff(date,baseDate)}}
function renderTemplates(){const el=$('#moreContent');el.innerHTML='<div class="card-grid" id="templateCards"></div>';const list=$('#templateCards');state.templates.slice().sort((a,b)=>Number(b.updatedAt)-Number(a.updatedAt)).forEach(t=>{const c=document.createElement('article');c.className='template-card';c.innerHTML=`<h3>${esc(t.name)}</h3><span class="meta">${t.type==='day'?'Día perfecto':'Semana perfecta'} · ${t.plans?.length||0} elemento(s)</span><div class="card-actions"><button class="btn small apply" type="button">Aplicar</button><button class="btn small rename" type="button">Renombrar</button><button class="btn small danger delete" type="button">Eliminar</button></div>`;c.querySelector('.apply').onclick=()=>applyTemplate(t);c.querySelector('.rename').onclick=()=>{const name=prompt('Nuevo nombre',t.name);if(name?.trim()){t.name=name.trim();t.updatedAt=now();persist('Plantilla renombrada');renderTemplates()}};c.querySelector('.delete').onclick=()=>{if(confirm(`¿Eliminar "${t.name}"?`)){removeFrom('templates',t.id);persist('Plantilla eliminada');renderTemplates()}};list.appendChild(c)});if(!list.children.length)list.innerHTML='<div class="empty-state">Guarda un día o una semana desde la pestaña Semana para repetirlos cuando quieras.</div>'}
function applyTemplate(t){const base=t.type==='day'?prompt('¿A qué fecha quieres aplicarlo? (AAAA-MM-DD)',localDateKey(mondayOf(viewWeekOffset))):localDateKey(mondayOf(viewWeekOffset));if(t.type==='day'&&!/^\d{4}-\d{2}-\d{2}$/.test(base||''))return;const hasExisting=t.plans.some(p=>getPlans(keyFor(addDays(base,p.dayOffset||0),p.slot)).length);let mode='add';if(hasExisting&&!confirm('Ya hay elementos planificados. Pulsa Aceptar para añadirlos o Cancelar para sustituirlos.'))mode='replace';if(mode==='replace'){const affected=new Set(t.plans.map(p=>keyFor(addDays(base,p.dayOffset||0),p.slot)));affected.forEach(k=>getPlans(k).forEach(p=>tombstone('plans',p.id)));affected.forEach(k=>delete state.plans[k])}let skipped=0;t.plans.forEach(p=>{if(p.kind==='inventory'){const item=state.inventory.find(i=>i.id===p.inventoryItemId);if(!item||availableQuantity(item)<Number(p.quantity||0)){skipped++;return}}addPlan(keyFor(addDays(base,p.dayOffset||0),p.slot),{kind:p.kind||'menu',menuId:p.menuId,inventoryItemId:p.inventoryItemId,itemName:p.itemName,quantity:p.quantity,unit:p.unit})});addHistory('applied_template',t.name);persist(skipped?`Plantilla aplicada; ${skipped} producto(s) sin existencias`:'Plantilla aplicada');switchPanel('weekPanel');renderAll()}

function buildAlerts(){const alerts=[],today=localDateKey(),tomorrow=addDays(today,1);state.inventory.forEach(item=>{const s=inventoryStatus(item);if(state.settings.notifyExpiry&&s.level!=='normal')alerts.push({id:`stock-${item.id}-${s.level}`,type:s.level,icon:s.level==='danger'?'🔴':'🟠',title:item.name,text:s.reasons.join(' · '),itemId:item.id});});Object.entries(state.plans).forEach(([key,plans])=>{const {date}=splitPlanKey(key);plans.filter(p=>!p.done).forEach(p=>{if(p.kind==='inventory'){const item=inventoryForPlan(p),info=CATEGORY_INFO[item?.category]||CATEGORY_INFO.other;if(item?.location==='freezer'&&date===tomorrow&&state.settings.notifyThaw&&!info.direct)alerts.push({id:`thaw-${p.id}-${date}`,type:'notice',icon:'❄️',title:`Pasa ${item.name} a la nevera`,text:`Mañana tienes previstos ${formatNumber(p.quantity)} ${p.unit||item.unit}. ${info.thaw}`});if(item?.location==='freezer'&&date===today&&state.settings.notifyThaw&&info.direct)alerts.push({id:`direct-${p.id}-${date}`,type:'notice',icon:'🍳',title:`Cocina ${item.name} directamente congelado`,text:info.thaw});if(date<today&&state.settings.notifyConfirm)alerts.push({id:`confirm-${p.id}`,type:'warning',icon:'✓',title:`Confirma si consumiste ${item?.name||p.itemName}`,text:`Estaba previsto para el ${fmtDate(date)} y sigue reservado.`})}else if(date<today&&!p.done&&state.settings.notifyConfirm)alerts.push({id:`confirm-menu-${p.id}`,type:'warning',icon:'✓',title:`¿Comisteis ${menuForPlan(p)?.name||'el menú'}?`,text:`Estaba previsto para el ${fmtDate(date)}.`})})});return alerts}
function renderAlertsBadge(){const alerts=buildAlerts(),badge=$('#alertCount');badge.textContent=alerts.length;badge.hidden=!alerts.length;maybeDeviceNotifications(alerts)}
function renderAlerts(container){container.innerHTML='';const alerts=buildAlerts();alerts.forEach(a=>{const c=document.createElement('article');c.className='alert-card';c.innerHTML=`<span class="alert-icon">${a.icon}</span><div><strong>${esc(a.title)}</strong><div class="meta">${esc(a.text)}</div></div>`;container.appendChild(c)});if(!alerts.length)container.innerHTML='<div class="empty-state">No hay avisos pendientes.</div>'}
function openAlerts(){renderAlerts($('#alertsDialogContent'));$('#alertsDialog').showModal()}
function maybeDeviceNotifications(alerts){if(!('Notification'in window)||Notification.permission!=='granted'||!alerts.length)return;const [hour,minute]=(state.settings.reminderTime||'20:00').split(':').map(Number),d=new Date();if(d.getHours()<hour||d.getHours()===hour&&d.getMinutes()<minute)return;const sent=JSON.parse(localStorage.getItem(NOTICE_KEY)||'{}'),today=localDateKey();alerts.slice(0,3).forEach(a=>{const key=`${today}:${a.id}`;if(sent[key])return;try{new Notification(a.title,{body:a.text,icon:'apple-touch-icon.png',tag:a.id});sent[key]=now()}catch{}});for(const k of Object.keys(sent))if(!k.startsWith(today))delete sent[k];localStorage.setItem(NOTICE_KEY,JSON.stringify(sent))}
function renderHistory(){const el=$('#moreContent');el.innerHTML='',discarded=state.history.filter(h=>h.action==='discarded_inventory'),waste=discarded.reduce((n,h)=>n+Number(h.quantity||0),0),byName={};discarded.forEach(h=>{const n=h.itemName||'Sin especificar';byName[n]=(byName[n]||0)+1});const frequent=Object.entries(byName).sort((a,b)=>b[1]-a[1])[0],summary=document.createElement('div');summary.className='info-strip';summary.textContent=`${state.history.length} movimientos registrados${waste?` · ${formatNumber(waste)} de cantidad desechada`:''}${frequent&&frequent[1]>1?` · se desecha más a menudo: ${frequent[0]}`:''}`;el.appendChild(summary);state.history.slice(0,80).forEach(h=>{const c=document.createElement('article');c.className='history-card';c.innerHTML=`<strong>${esc(historyLabel(h.action))}</strong><div>${esc(h.detail)}</div><time>${new Date(h.at).toLocaleString('es-ES')}</time>`;el.appendChild(c)});if(!state.history.length)el.innerHTML+='<div class="empty-state">El historial aparecerá al consumir, mover, cambiar o eliminar productos.</div>'}
function historyLabel(action){return({consumed_menu:'Menú consumido',unconfirmed_menu:'Confirmación deshecha',swapped_menu:'Menú sustituido',leftovers:'Sobras registradas',deleted_menu:'Menú eliminado',consumed_inventory:'Producto consumido',discarded_inventory:'Producto desechado',moved_inventory:'Producto movido',applied_template:'Plantilla aplicada',inventory_planned:'Producto reservado'}[action]||'Cambio')}
function openTips(){const el=$('#tipsContent');el.innerHTML=`<section><h3>Reglas básicas</h3><p>Conserva el congelador a <strong>−18 °C o menos</strong>, etiqueta la fecha y utiliza primero los lotes más antiguos.</p><p>Descongela en la nevera, con agua fría controlada o en microondas si vas a cocinar inmediatamente; no sobre la encimera.</p><p>Los plazos de la app indican principalmente calidad. Sigue siempre la fecha e instrucciones del fabricante.</p></section>`+Object.values(CATEGORY_INFO).map(x=>`<section><h3>${esc(x.label)}</h3><p><strong>Congelar:</strong> ${esc(x.freeze)}</p><p><strong>Descongelar:</strong> ${esc(x.thaw)}</p><p><strong>Después:</strong> ${esc(x.after)}</p></section>`).join('')+`<section><h3>Pescado para consumir crudo</h3><p>Como precaución frente al anisakis, en congelador doméstico debe mantenerse al menos cinco días completos desde que se introduce. Si el congelador no alcanza la temperatura necesaria, compra el pescado ya congelado.</p></section><section><h3>Referencias</h3><p>Consejos basados en las recomendaciones de AESAN y las tablas de conservación de USDA/FoodSafety.gov. Consulta siempre el etiquetado del producto.</p></section>`;$('#tipsDialog').showModal()}
function openItemAdvice(item){const info=CATEGORY_INFO[item.category]||CATEGORY_INFO.other;$('#tipsContent').innerHTML=`<section><h3>${esc(item.name)}</h3><p><strong>Categoría:</strong> ${esc(info.label)}</p><p><strong>Cómo descongelar:</strong> ${esc(info.thaw)}</p><p><strong>Después:</strong> ${esc(info.after)}</p>${/fish/.test(item.category)?'<p><strong>Si se consumirá crudo:</strong> mantenlo congelado cinco días completos como precaución frente al anisakis.</p>':''}</section>`;$('#tipsDialog').showModal()}

function autoStats(){const menuPlans=Object.entries(state.plans).flatMap(([k,list])=>list.filter(p=>p.kind==='menu').map(p=>({k,p}))),weeks=new Set(menuPlans.map(x=>{const d=parseDate(x.k.slice(0,10)),m=new Date(d);m.setDate(m.getDate()-((m.getDay()+6)%7));return localDateKey(m)}));return{plans:menuPlans.length,weeks:weeks.size,unlocked:menuPlans.length>=20&&weeks.size>=3}}
function renderAutoUnlock(){const s=autoStats(),card=$('#autoProgress'),button=$('#autoWeekBtn');button.disabled=!s.unlocked;card.hidden=s.unlocked;if(!s.unlocked)card.innerHTML=`La generación automática se activará con 3 semanas y 20 comidas o cenas planificadas. Progreso: <strong>${Math.min(s.weeks,3)}/3 semanas</strong> · <strong>${Math.min(s.plans,20)}/20 planificaciones</strong>.`}
function menuFrequency(){const f={};Object.values(state.plans).flat().forEach(p=>{if(p.kind==='menu')f[p.menuId]=(f[p.menuId]||0)+1});state.templates.forEach(t=>t.plans?.forEach(p=>{if(p.kind!=='inventory'&&p.menuId)f[p.menuId]=(f[p.menuId]||0)+2}));return f}
function recentMenuIds(days=10){const min=addDays(localDateKey(),-days),ids=new Set();Object.entries(state.plans).forEach(([k,list])=>{if(k.slice(0,10)>=min&&k.slice(0,10)<=localDateKey())list.forEach(p=>{if(p.kind==='menu')ids.add(p.menuId)})});return ids}
function conflictTags(menu,date,slot,draft){const tags=new Set(menu.tags||[]);if(!tags.size)return false;const relevant=draft.filter(x=>x.menuId&&(x.date===date&&x.slot!==slot||Math.abs(dayDiff(x.date,date))===1));return relevant.some(x=>{const other=state.menus.find(m=>m.id===x.menuId);return(other?.tags||[]).some(t=>tags.has(t))})}
function chooseAutoMenu(date,slot,draft,frequency,recent){let candidates=state.menus.filter(m=>!m.noSuggest&&(m.type==='both'||m.type===slot));if(!candidates.length)return null;const strict=candidates.filter(m=>!conflictTags(m,date,slot,draft));if(strict.length)candidates=strict;const sameWeek=new Map(draft.map(x=>[x.menuId,(draft.filter(y=>y.menuId===x.menuId).length)]));const scored=candidates.map(m=>{let score=1+(frequency[m.id]||0)*1.5+(m.favorite?8:0);if(recent.has(m.id))score-=5;score-=Number(sameWeek.get(m.id)||0)*7;score+=Math.random()*3;return{m,score}}).sort((a,b)=>b.score-a.score);return scored[0]?.m||null}
function generateAutoDraft(keepLocks=false){const frequency=menuFrequency(),recent=recentMenuIds(),dates=weekKeys(),old=autoDraft;autoDraft=[];dates.forEach(date=>['meal','dinner'].forEach(slot=>{const locked=keepLocks&&old.find(x=>x.date===date&&x.slot===slot&&x.locked);if(locked){autoDraft.push({...locked});return}const menu=chooseAutoMenu(date,slot,autoDraft,frequency,recent);autoDraft.push({date,slot,menuId:menu?.id||'',locked:false})}));renderAutoProposal()}
function openAutoWeek(){if(!autoStats().unlocked){toast('Aún faltan datos de uso para generar una semana fiable');return}generateAutoDraft(false);$('#autoDialog').showModal()}
function renderAutoProposal(){const el=$('#autoProposal');el.innerHTML='';autoDraft.forEach((x,index)=>{const row=document.createElement('div');row.className='proposal-row';const options=state.menus.filter(m=>m.type==='both'||m.type===x.slot).sort(sortByName).map(m=>`<option value="${m.id}" ${m.id===x.menuId?'selected':''}>${esc(m.name)}</option>`).join('');row.innerHTML=`<strong>${esc(fmtDate(x.date,{weekday:'short',day:'numeric'}))} · ${x.slot==='meal'?'Comida':'Cena'}</strong><select aria-label="Menú">${options}</select><label><input type="checkbox" ${x.locked?'checked':''}> Bloquear</label>`;row.querySelector('select').onchange=e=>{autoDraft[index].menuId=e.target.value};row.querySelector('input').onchange=e=>{autoDraft[index].locked=e.target.checked};el.appendChild(row)})}
function applyAuto(mode){if(mode==='replace'){weekPlanEntries().forEach(([k,list])=>list.forEach(p=>tombstone('plans',p.id)));weekPlanEntries().forEach(([k])=>delete state.plans[k])}autoDraft.filter(x=>x.menuId).forEach(x=>addPlan(keyFor(x.date,x.slot),{menuId:x.menuId}));addHistory('applied_template','Semana generada automáticamente');persist('Semana automática aplicada');$('#autoDialog').close();renderAll()}

function switchPanel(panelId){$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===panelId));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===panelId));if(panelId==='morePanel')renderMore();window.scrollTo({top:0,behavior:'smooth'})}
function openSettings(){const s=state.settings;$('#allergenTerms').value=s.allergens.join(', ');$('#reminderTime').value=s.reminderTime||'20:00';$('#notifyThaw').checked=Boolean(s.notifyThaw);$('#notifyExpiry').checked=Boolean(s.notifyExpiry);$('#notifyConfirm').checked=Boolean(s.notifyConfirm);$('#notificationPermissionBtn').textContent='Notification'in window&&Notification.permission==='granted'?'Notificaciones permitidas':'Permitir notificaciones del dispositivo';$('#settingsDialog').showModal()}

$('#menuForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#menuId').value,t=now(),data={id:id||uid(),name:$('#menuName').value.trim(),type:$('#menuType').value,time:$('#menuTime').value.trim(),ingredients:draftIngredients.map(i=>({...i})),tags:[...$('#menuTags').selectedOptions].map(o=>o.value),favorite:$('#menuFavorite').checked,noSuggest:$('#menuNoSuggest').checked,notes:$('#menuNotes').value.trim(),updatedAt:t};if(!data.name)return;const index=state.menus.findIndex(m=>m.id===id);if(index>=0)state.menus[index]=data;else state.menus.push(data);if(!id&&pendingMenuSlot)addPlan(keyFor(pendingMenuSlot.date,pendingMenuSlot.slot),{menuId:data.id});pendingMenuSlot=null;persist(id?'Menú actualizado':'Menú creado');$('#menuDialog').close();renderAll()});
$('#inventoryForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#inventoryId').value,category=$('#inventoryCategory').value;let allergens=[];try{allergens=JSON.parse($('#inventoryAllergens').value||'[]')}catch{}const item={id:id||uid(),name:$('#inventoryName').value.trim(),brand:$('#inventoryBrand').value.trim(),barcode:$('#inventoryBarcode').value.replace(/\D/g,''),location:$('#inventoryLocation').value,category,quantity:Number($('#inventoryQuantity').value),unit:$('#inventoryUnit').value,storedAt:$('#inventoryStoredAt').value,expiryAt:$('#inventoryExpiry').value,openedAt:$('#inventoryOpenedAt').value,qualityDays:Number($('#inventoryQualityDays').value)||CATEGORY_INFO[category]?.days||90,notes:$('#inventoryNotes').value.trim(),imageUrl:safeUrl($('#inventoryImage').value),allergens,updatedAt:now()};if(!item.name||!(item.quantity>0)||!item.storedAt)return;const matches=allergenMatches(item.name,item.allergens);if(matches.length&&!confirm(`Este producto puede contener ${matches.join(', ')}. ¿Quieres guardarlo igualmente?`))return;const index=state.inventory.findIndex(x=>x.id===id);if(index>=0)state.inventory[index]=item;else state.inventory.push(item);addHistory(id?'updated_inventory':'added_inventory',`${item.name} · ${formatNumber(item.quantity)} ${item.unit} · ${LOCATION_LABEL[item.location]}`);persist(id?'Producto actualizado':'Producto añadido');$('#inventoryDialog').close();currentInventoryLocation=item.location;syncInventoryTabs();renderAll();if(!id&&item.location==='freezer')setTimeout(()=>toast(`Consejo: ${(CATEGORY_INFO[category]||CATEGORY_INFO.other).freeze}`),900)});
$('#placementForm').addEventListener('submit',e=>{e.preventDefault();const item=state.inventory.find(x=>x.id===$('#placementItemId').value),planId=e.currentTarget.dataset.planId,oldKey=e.currentTarget.dataset.oldKey,date=$('#placementDate').value,slot=$('#placementSlot').value,quantity=Number($('#placementQuantity').value);if(!item||!date||!(quantity>0))return;const existing=planId&&getPlans(oldKey).find(x=>x.id===planId),max=availableQuantity(item,planId);if(quantity>max){toast(`Solo hay ${formatNumber(max)} ${item.unit} disponibles`);return}const newKey=keyFor(date,slot);if(existing){state.plans[oldKey]=getPlans(oldKey).filter(x=>x.id!==planId);if(!state.plans[oldKey].length)delete state.plans[oldKey];(state.plans[newKey]??=[]).push({...existing,quantity,unit:item.unit,done:false,updatedAt:now()})}else addPlan(newKey,{kind:'inventory',inventoryItemId:item.id,itemName:item.name,quantity,unit:item.unit});addHistory('inventory_planned',`${formatNumber(quantity)} ${item.unit} de ${item.name} · ${fmtDate(date)} ${slot==='meal'?'comida':'cena'}`);persist('Cantidad reservada');$('#placementDialog').close();renderAll()});
$('#consumeForm').addEventListener('submit',e=>{e.preventDefault();const key=$('#consumePlanKey').value,id=$('#consumePlanId').value,p=getPlans(key).find(x=>x.id===id),item=p&&inventoryForPlan(p),qty=Number($('#consumeQuantity').value);if(!p||!item||qty<0||qty>Math.min(Number(item.quantity),Number(p.quantity))){toast('Cantidad no válida');return}if(qty>0){item.quantity=Number((item.quantity-qty).toFixed(2));item.updatedAt=now();addHistory('consumed_inventory',`${formatNumber(qty)} ${item.unit} de ${item.name}`,{itemId:item.id,quantity:qty});if(item.quantity<=0)removeFrom('inventory',item.id)}else addHistory('inventory_not_consumed',`${item.name} no se consumió`);p.done=true;p.consumedQuantity=qty;p.updatedAt=now();persist(qty?'Consumo confirmado':'Marcado como no consumido');$('#consumeDialog').close();renderAll()});
$('#quickShopForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#shopName').value.trim();if(!name)return;state.shop.push({id:uid(),name,quantity:$('#shopQuantity').value?Number($('#shopQuantity').value):null,unit:$('#shopUnit').value,category:shopCategory(name),done:false,source:'manual',updatedAt:now()});$('#shopName').value='';$('#shopQuantity').value='';$('#shopUnit').value='';persist('Producto añadido');renderShop()});
$('#templateForm').addEventListener('submit',e=>{e.preventDefault();const type=$('#templateType').value,date=$('#templateDate').value,name=$('#templateName').value.trim();if(!name)return;let plans,base;if(type==='day'){base=date;plans=[...getPlans(keyFor(date,'meal')).map(p=>serializePlan(p,keyFor(date,'meal'),base)),...getPlans(keyFor(date,'dinner')).map(p=>serializePlan(p,keyFor(date,'dinner'),base))]}else{base=localDateKey(mondayOf(viewWeekOffset));plans=weekPlanEntries().flatMap(([k,list])=>list.map(p=>serializePlan(p,k,base)))}state.templates.push({id:uid(),type,name,plans,updatedAt:now()});persist('Plantilla guardada');$('#templateDialog').close();renderAll()});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();state.settings={allergens:$('#allergenTerms').value.split(',').map(x=>x.trim()).filter(Boolean),reminderTime:$('#reminderTime').value||'20:00',notifyThaw:$('#notifyThaw').checked,notifyExpiry:$('#notifyExpiry').checked,notifyConfirm:$('#notifyConfirm').checked};persist('Ajustes guardados');$('#settingsDialog').close();renderAll()});

$('#addIngredientBtn').onclick=addDraftIngredient;$('#ingredientInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addDraftIngredient()}});
$('#addMenuBtn').onclick=$('#addMenuBtn2').onclick=()=>editMenu();$('#addInventoryBtn').onclick=()=>openInventoryForm();$('#scanInventoryBtn').onclick=openScanner;$('#tipsBtn').onclick=openTips;$('#alertsBtn').onclick=openAlerts;$('#settingsBtn').onclick=openSettings;$('#undoBtn').onclick=undo;$('#refreshBtn').onclick=()=>loadRemote(true);$('#clearCompletedBtn').onclick=clearCompletedShopping;
$('#prevWeek').onclick=()=>{viewWeekOffset--;localStorage.setItem(VIEW_KEY,String(viewWeekOffset));renderAll()};$('#nextWeek').onclick=()=>{viewWeekOffset++;localStorage.setItem(VIEW_KEY,String(viewWeekOffset));renderAll()};$('#saveWeekTemplateBtn').onclick=()=>openTemplateSave('week');$('#autoWeekBtn').onclick=openAutoWeek;
$('#inventoryName').addEventListener('blur',()=>{if(!$('#inventoryId').value){const c=categoryForName($('#inventoryName').value);$('#inventoryCategory').value=c;$('#inventoryQualityDays').value=CATEGORY_INFO[c]?.days||90}updateInventoryForm()});$('#inventoryBrand').addEventListener('input',updateInventoryForm);$('#inventoryCategory').addEventListener('change',()=>{$('#inventoryQualityDays').value=CATEGORY_INFO[$('#inventoryCategory').value]?.days||90;updateInventoryForm()});$('#inventoryLocation').addEventListener('change',updateInventoryForm);
$('#lookupBarcodeBtn').onclick=()=>lookupBarcode();$('#closeScannerBtn').onclick=async()=>{await stopScanner();$('#scannerDialog').close()};$('#scannerDialog').addEventListener('close',stopScanner);$('#reprogramBtn').onclick=reprogramPlan;
$('#regenerateBtn').onclick=()=>generateAutoDraft(true);$('#applyAutoAddBtn').onclick=()=>applyAuto('add');$('#applyAutoReplaceBtn').onclick=()=>applyAuto('replace');
$('#notificationPermissionBtn').onclick=async()=>{if(!('Notification'in window)){toast('Este navegador no admite notificaciones');return}const result=await Notification.requestPermission();$('#notificationPermissionBtn').textContent=result==='granted'?'Notificaciones permitidas':'Permiso no concedido';if(result==='granted')toast('Notificaciones activadas')};
$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));$$('#inventoryTabs button').forEach(b=>b.onclick=()=>{currentInventoryLocation=b.dataset.location;syncInventoryTabs();renderInventory()});$$('#moreTabs button').forEach(b=>b.onclick=()=>{currentMoreTab=b.dataset.more;renderMore()});$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
window.addEventListener('beforeunload',()=>localStorage.setItem(KEY,JSON.stringify(state)));

populateCategories();syncInventoryTabs();renderAll();loadRemote(false);
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
